[package]
name = "transaction-proccessor"
version = "0.1.0"
authors = ["Hector Ramirez <github.hector1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "^1.0"

